# Generated by Django 4.0.5 on 2022-07-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='clothes_description',
            field=models.TextField(null=True),
        ),
    ]
