# Generated by Django 5.0.1 on 2024-02-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_alter_cart_user_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='hashed_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
